### ISSUE TITLE
Publish to pypi when release is tagged

### ISSUE THREAD

**Issue by wfvining** [pvlib/pvanalytics#11]
Configure github action to build and publish packages on pypi when a release is tagged and all tests have passed.

This can be added as a new job to the "lint and test" workflow using the `needs` key

```yaml
jobs:

  # [...]

  publish: 
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == "release" # ???

    steps:
      # checkout, setup-python, install setuptools and twine, build package, upload package
```

**Comment by wfvining** [comment]
Alternatively, we can create a separate workflow that runs only when a release is published

```yaml
on:
  release:
    types: [published]
```
